proxy:
  title: Office National des Forêts
  logo-url: file:///opt/shinyproxy/logo_onf.jpg
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  container-wait-time: 100000
  port: 8080
  authentication: simple
  admin-groups: admingroup
  # Example: 'simple' authentication configuration
  users:
  - name: po76844
    password: Password07
    groups: admingroup
  - name: tds
    password: tds
    groups: users
  # Docker configuration
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    # internal-networking: true
  specs:
  - id: Daizy-DB
    display-name: Daizy-DB
    description: Modification de base de données de l'application Désignation Mobile
    container-cmd: ["R", "-e", "shiny::runApp('/root/daizy-db')"]
    container-image: pobsteta/daizy-db
    access-groups: [admingroup,users]
    # container-network: "host"
    
logging:
  file:
    shinyproxy.log
