shiny:
  proxy:
    title: Office National des Forêts
    logo-url: file:///opt/shinyproxy/logo_onf.jpg
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    container-wait-time: 100000
    port: 8090
    authentication: simple
    admin-groups: admingroup
    # Example: 'simple' authentication configuration
    users:
    - name: po76844
      password: Password07
      groups: admingroup
    - name: tds
      password: tds
      groups: users
    # Example: 'ldap' authentication configuration
    ldap:
      #- url: ldap://ldap.forumsys.com:389/dc=example,dc=com
      #  user-dn-pattern: uid={0}
      #  group-search-base:
      #  group-search-filter: (uniqueMember={0})
      #  manager-dn: cn=read-only-admin,dc=example,dc=com
      #  manager-password: password
      - url: ldap://ldap.onf.fr:389/o=onf.fr
        user-dn-pattern: 
        group-search-base: o=onf.fr
        group-search-filter: 
        manager-dn: 
        manager-password: 
    # Docker configuration
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      internal-networking: true
  apps:
  - name: Daizy-DB
    display-name: Daizy-DB
    description: Modification de base de données de l'application Désignation Mobile
    docker-cmd: ["R", "-e", "shiny::runApp('/root/daizy-db')"]
    docker-image: pobsteta/daizy-db
    groups: [admingroup,users]
    docker-network: "host"
    
logging:
  file:
    shinyproxy.log
